//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartament
    {
        public int ID_Apartaments { get; set; }
        public int HouseID { get; set; }
        public int Number { get; set; }
        public decimal Area { get; set; }
        public int CountOfRooms { get; set; }
        public int Section { get; set; }
        public int Floor { get; set; }
        public int IsSold { get; set; }
        public int apartmentC { get; set; }
        public int ApartmentValueAdded { get; set; }
        public int IsDeleted { get; set; }
    
        public virtual House House { get; set; }
    }
}
