//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public House()
        {
            this.Apartaments = new HashSet<Apartament>();
        }
    
        public int ID_House { get; set; }
        public int ResidentialComplexID { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
        public decimal houseC { get; set; }
        public decimal HouseValueAdded { get; set; }
        public int IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartament> Apartaments { get; set; }
        public virtual ResidentialComplex ResidentialComplex { get; set; }
    }
}
