//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1
{
    using System;
    using System.Collections.Generic;
    
    public partial class rez33
    {
        public int ID { get; set; }
        public string НаименованиеЖК { get; set; }
        public string Дом { get; set; }
        public string Квартира { get; set; }
        public Nullable<decimal> Прибыль { get; set; }
    }
}
